# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -coverprofile=./cover.out
    
    - name: check test coverage
      uses: vladopajic/go-test-coverage@v2
      with:
        # Configure action using config file (option 1)
        config: ./.testcoverage.yml
        
        # Configure action by specifying input parameters individually (option 2)
        profile: cover.out
        local-prefix: github.com/nattask/nattask
        threshold-file: 70
        threshold-package: 80
        threshold-total: 85
