name: golangci-lint
on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: golangci/checkout@v3
      - uses: golangci/setup-go@v4
        with:
          go-version: "1.21"
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          skip-go-instalation: true
          args: --timeout=30m -verbose
          only-new-issues: true
            
